config.load_autoconfig()

config.set(
	"editor.command",
	["alacritty", "-e", "helix", "{file}", "-c", "normal {line}G{column0}l"],
)
config.set("fonts.default_family", ["Cartograph CF", "sans-serif"])

# Dark green theme
config.set("colors.webpage.bg", "#0b0f0c")
config.set("colors.webpage.preferred_color_scheme", "dark")
config.set("colors.webpage.darkmode.enabled", True)
config.set("colors.tabs.bar.bg", "#0e1411")
config.set("colors.tabs.odd.bg", "#0e1411")
config.set("colors.tabs.even.bg", "#0f1713")
config.set("colors.tabs.selected.odd.bg", "#14261e")
config.set("colors.tabs.selected.even.bg", "#14261e")
config.set("colors.tabs.odd.fg", "#cfe6d4")
config.set("colors.tabs.even.fg", "#cfe6d4")
config.set("colors.tabs.selected.odd.fg", "#e7f6ea")
config.set("colors.tabs.selected.even.fg", "#e7f6ea")
config.set("colors.statusbar.normal.bg", "#0e1411")
config.set("colors.statusbar.normal.fg", "#cfe6d4")
config.set("colors.statusbar.command.bg", "#14261e")
config.set("colors.statusbar.command.fg", "#e7f6ea")
config.set("colors.statusbar.url.fg", "#a8d8b5")
config.set("colors.statusbar.url.hover.fg", "#e7f6ea")
config.set("colors.statusbar.url.success.http.fg", "#7fcf9b")
config.set("colors.statusbar.url.success.https.fg", "#7fcf9b")
config.set("colors.statusbar.url.warn.fg", "#e6c76b")
config.set("colors.statusbar.url.error.fg", "#e6837b")
config.set("colors.completion.category.bg", "#0e1411")
config.set("colors.completion.category.fg", "#cfe6d4")
config.set("colors.completion.even.bg", "#0f1713")
config.set("colors.completion.odd.bg", "#0e1411")
config.set("colors.completion.fg", "#cfe6d4")
config.set("colors.completion.item.selected.bg", "#14261e")
config.set("colors.completion.item.selected.fg", "#e7f6ea")
config.set("colors.completion.scrollbar.bg", "#0e1411")
config.set("colors.completion.scrollbar.fg", "#2a4a3b")
config.set("url.searchengines", {"DEFAULT": "https://www.google.com/search?q={}"})
config.set("url.default_page", "https://www.google.com")
config.set("url.start_pages", ["https://www.google.com"])

# Sidebar-style tabs (keeps current theme colors)
config.set("tabs.position", "left")
config.set("tabs.width", 200)
config.set("tabs.min_width", 40)
config.set("tabs.max_width", 200)
config.set("tabs.title.format", "{audio}{index}: {current_title}")
config.set("tabs.title.format_pinned", "{audio}{index}")
config.set("tabs.favicons.show", "always")
config.set("tabs.padding", {"bottom": 6, "left": 10, "right": 10, "top": 6})
config.set("tabs.indicator.width", 3)
config.set("tabs.indicator.padding", {"bottom": 0, "left": 0, "right": 6, "top": 0})
config.set("tabs.last_close", "close")
config.set("tabs.show", "multiple")
config.set("tabs.mousewheel_switching", False)
config.set("tabs.pinned.shrink", True)
config.set("tabs.pinned.frozen", True)
config.set("tabs.new_position.related", "next")
config.set("tabs.new_position.unrelated", "last")
config.set("tabs.select_on_remove", "prev")
config.set("tabs.background", True)
config.set("auto_save.session", True)
config.bind("<Ctrl-Shift-d>", "open -t file:///home/div/Downloads")

config.bind("<Alt-t>", "config-cycle tabs.show always never")
config.bind("<Alt-b>", "config-cycle statusbar.show always never")
config.bind(
	"<Alt-s>",
	"config-cycle tabs.show always never ;; config-cycle statusbar.show always never",
)
