# Archived i3bar block; the active i3 setup now uses Polybar.
bar {
  status_command i3status-rs /home/div/repo/linuxconffiles/archive/i3bar/i3status-rust/config.toml
  # status_command i3status
  i3bar_command i3bar -t
  output DisplayPort-0

  position top
  font pango:Cartograph CF 12
  padding 1px

  colors {
    background #001A0FBB
    # statusline #FFFFFFFF
    # separator  #B3FF00

    focused_workspace  #4CBB17 #b3ff00 #000000
    inactive_workspace #00000066 #00000066 #FFFFFF
  }
}
