general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor = HDMI-A-1
    path = /home/div/pics/wallpapersV/961f3a2ce5d5412a4dbdb30374543a74ba6f2f70.png
}

background {
    monitor = DP-1
    path = /home/div/pics/wallpapers/wallpapersden.com_blade-runner-2049-movie-joi-and-k_3000x1875.jpg
}

background {
    monitor = DP-2
    path = /home/div/pics/wallpapersS/2020-03-24-die-for-honor.jpg
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    rounding = -1
    outer_color = rgb(89b4fa)
    inner_color = rgba(1e1e2e99)
    font_color = rgb(cdd6f4)
    check_color = rgb(a6e3a1)
    fail_color = rgb(f38ba8)
    capslock_color = rgb(fab387)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, 0
    halign = center
    valign = center
}
