Bindings:
map J nextTab
map K previousTab

Styling:
div > .vimiumHintMarker {
  background: #002b00;
  border: 1px solid #b3ff00;
  padding: 0px 2px;
  border-radius: 2px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.5);
}
div > .vimiumHintMarker span {
  color: #b3ff00;
  font-weight: bold;
  font-size: 14px;
  line-height: 16px;
}
div > .vimiumHintMarker > .matchingCharacter {
  color: #ffffff;
}