wallpaper {
    monitor = DP-2
    path = /home/div/pics/wallpapersS_safe/245085.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/div/pics/wallpapers_safe/1770759436804440.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/div/pics/wallpapersV_safe/961f3a2ce5d5412a4dbdb30374543a74ba6f2f70.png
    fit_mode = cover
}

splash = false
